Math magicians: components
Rustamxon7/Math-Magicians pull request #2
Opened 2021-09-21 16:27 UTC by Rustamxon7

**I have completed all the requirements:**

- Deleted all unused files. ✅
- Created components directory. ✅
- Calculator.js created. ✅
- Used class-based components. ✅
- Tested on browser if it is working or not. ✅

Feel free to review -🧑🏻‍💻- my code and let me know if there are any changes to do.-🤓-😉-

2021-09-21 21:21 UTC, EricMbouwe requested changes
Hi @Rustamxon7, 🙋‍♂️

Good job so far!

- Nice looking readme 👍
- Descriptive commit messages 👍
- Well written PR 👍

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-21 21:21 UTC, EricMbouwe commented on src/components/Calculator.js
> +  }
- [ ] As mentioned above you don't need a state here 😉. Let's remove it for now 🙂.

2021-09-21 21:21 UTC, EricMbouwe commented on src/index.css
> +}
- [ ] The keypad on your calculator does not match the given design as required for this project. The options buttons don't have the appropriate background color. I have noticed that you added a `className="options"` to them, please go ahead and add that background color to that selector.

![Screenshot from 2021-09-21 22-02-33](https://user-images.githubusercontent.com/40503704/134248360-2852ab7d-d189-41be-b1cb-b788c721c201.png) 
![Screenshot from 2021-09-21 22-12-47](https://user-images.githubusercontent.com/40503704/134248511-ad83ed82-a254-46a7-8685-e6d36d05700d.png)

2021-09-21 21:21 UTC, EricMbouwe commented on src/App.js
> +  }
- [ ] Humm... At this point, you don't need a state here 😉. You can double-check the requirements `Develop just the UI of the calculator; the math logic to make it work will be added in the next project.` Let's remove it for now 🙂.

2021-09-22 03:37 UTC, BrianSammit approved these changes
# STATUS: APROVED :green_circle: :clap: 

Hello @Rustamxon7, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-22 06:58 UTC, merged